"""added dominant emotion

Revision ID: 25fd1335064e
Revises: 495aad747f09
Create Date: 2024-09-29 15:52:15.888011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fd1335064e'
down_revision = '495aad747f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_table', schema=None) as batch_op:
        batch_op.drop_column('dominant_emotion')

    # ### end Alembic commands ###
