"""fixed some naming issues

Revision ID: 495aad747f09
Revises: e4c6f46417eb
Create Date: 2024-09-28 02:23:55.308595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '495aad747f09'
down_revision = 'e4c6f46417eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    # ### end Alembic commands ###
