"""changing field name

Revision ID: 5f1ec3509952
Revises: 
Create Date: 2024-09-27 14:33:48.374739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f1ec3509952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
